import { Product, Meal } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'APT-001',
    name: 'Premium Pasta Penne',
    description: 'High-quality durum wheat pasta, perfect for institutional kitchens',
    category: 'Pasta & Grains',
    price: 24.99,
    bulkPrice: 19.99,
    bulkMinQuantity: 10,
    unit: '5kg box',
    imageUrl: 'https://images.unsplash.com/photo-1551462147-37e33d21e5c6?w=400&h=300&fit=crop',
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 350,
      protein: 12,
      carbs: 70,
      fat: 2,
    },
    inStock: true,
  },
  {
    id: '2',
    sku: 'APT-002',
    name: 'Organic Tomato Sauce',
    description: 'Rich tomato sauce made from Italian tomatoes',
    category: 'Sauces & Condiments',
    price: 18.50,
    bulkPrice: 15.99,
    bulkMinQuantity: 12,
    unit: '3L can',
    imageUrl: 'https://images.unsplash.com/photo-1605521560596-83f6afe9d2d2?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 45,
      protein: 2,
      carbs: 8,
      fat: 1,
    },
    inStock: true,
  },
  {
    id: '3',
    sku: 'APT-003',
    name: 'Fresh Mozzarella Cheese',
    description: 'Creamy mozzarella cheese, ideal for pizza and pasta dishes',
    category: 'Dairy',
    price: 32.00,
    bulkPrice: 28.00,
    bulkMinQuantity: 6,
    unit: '2kg pack',
    imageUrl: 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400&h=300&fit=crop',
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 280,
      protein: 22,
      carbs: 3,
      fat: 21,
    },
    inStock: true,
  },
  {
    id: '4',
    sku: 'APT-004',
    name: 'Almond Flour',
    description: 'Finely ground almond flour for gluten-free baking',
    category: 'Baking',
    price: 45.00,
    bulkPrice: 39.99,
    bulkMinQuantity: 8,
    unit: '3kg bag',
    imageUrl: 'https://images.unsplash.com/photo-1585543921377-e2a0e8b8f0c0?w=400&h=300&fit=crop',
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 575,
      protein: 21,
      carbs: 21,
      fat: 50,
    },
    inStock: true,
  },
  {
    id: '5',
    sku: 'APT-005',
    name: 'Extra Virgin Olive Oil',
    description: 'Cold-pressed olive oil from Spanish groves',
    category: 'Oils & Fats',
    price: 55.00,
    bulkPrice: 48.00,
    bulkMinQuantity: 4,
    unit: '5L bottle',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fat: 100,
    },
    inStock: true,
  },
  {
    id: '6',
    sku: 'APT-006',
    name: 'Gluten-Free Bread Mix',
    description: 'Premium bread mix without gluten, easy preparation',
    category: 'Baking',
    price: 38.00,
    bulkPrice: 34.00,
    bulkMinQuantity: 10,
    unit: '4kg box',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    allergens: ['eggs'],
    nutritionalInfo: {
      calories: 340,
      protein: 8,
      carbs: 68,
      fat: 4,
    },
    inStock: true,
  },
  {
    id: '7',
    sku: 'APT-007',
    name: 'Chicken Breast Fillet',
    description: 'Fresh frozen chicken breast, premium quality',
    category: 'Poultry',
    price: 68.00,
    bulkPrice: 62.00,
    bulkMinQuantity: 5,
    unit: '5kg pack',
    imageUrl: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
    },
    inStock: true,
  },
  {
    id: '8',
    sku: 'APT-008',
    name: 'Wild Salmon Fillet',
    description: 'Sustainably sourced wild salmon, frozen',
    category: 'Seafood',
    price: 95.00,
    bulkPrice: 85.00,
    bulkMinQuantity: 4,
    unit: '3kg pack',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    allergens: ['fish'],
    nutritionalInfo: {
      calories: 208,
      protein: 25,
      carbs: 0,
      fat: 13,
    },
    inStock: true,
  },
  {
    id: '9',
    sku: 'APT-009',
    name: 'Brown Rice',
    description: 'Whole grain brown rice, nutrient-rich',
    category: 'Pasta & Grains',
    price: 22.00,
    bulkPrice: 18.50,
    bulkMinQuantity: 15,
    unit: '10kg bag',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 370,
      protein: 8,
      carbs: 77,
      fat: 3,
    },
    inStock: true,
  },
  {
    id: '10',
    sku: 'APT-010',
    name: 'Soy Sauce',
    description: 'Traditional brewed soy sauce for Asian cuisine',
    category: 'Sauces & Condiments',
    price: 16.00,
    bulkPrice: 13.50,
    bulkMinQuantity: 12,
    unit: '2L bottle',
    imageUrl: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400&h=300&fit=crop',
    allergens: ['soy', 'gluten'],
    nutritionalInfo: {
      calories: 60,
      protein: 8,
      carbs: 6,
      fat: 0,
    },
    inStock: true,
  },
  {
    id: '11',
    sku: 'APT-011',
    name: 'Mixed Vegetables',
    description: 'Flash-frozen vegetable mix with carrots, peas, corn',
    category: 'Vegetables',
    price: 28.00,
    bulkPrice: 24.00,
    bulkMinQuantity: 8,
    unit: '4kg bag',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 3,
      carbs: 13,
      fat: 0.5,
    },
    inStock: true,
  },
  {
    id: '12',
    sku: 'APT-012',
    name: 'Parmesan Cheese Grated',
    description: 'Aged Parmesan cheese, pre-grated for convenience',
    category: 'Dairy',
    price: 48.00,
    bulkPrice: 42.00,
    bulkMinQuantity: 6,
    unit: '1kg container',
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=300&fit=crop',
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 431,
      protein: 38,
      carbs: 4,
      fat: 29,
    },
    inStock: true,
  },
];

export const ALLERGEN_LABELS: Record<string, { label: string; color: string }> = {
  nuts: { label: 'Nuts', color: 'bg-destructive text-destructive-foreground' },
  dairy: { label: 'Dairy', color: 'bg-warning text-warning-foreground' },
  gluten: { label: 'Gluten', color: 'bg-warning text-warning-foreground' },
  eggs: { label: 'Eggs', color: 'bg-warning text-warning-foreground' },
  soy: { label: 'Soy', color: 'bg-muted text-muted-foreground' },
  fish: { label: 'Fish', color: 'bg-destructive text-destructive-foreground' },
  shellfish: { label: 'Shellfish', color: 'bg-destructive text-destructive-foreground' },
  sesame: { label: 'Sesame', color: 'bg-muted text-muted-foreground' },
};

export const CONVERSATION_STARTERS = [
  "Find me budget-friendly protein options",
  "I need a gluten-free meal plan for lunch",
  "Show me high-protein, low-fat products",
  "What are my options for vegan breakfast?",
];

export const AGENT_CONVERSATION_STARTERS: Record<string, string[]> = {
  auto: [
    "Find me budget-friendly protein options",
    "I need a gluten-free meal plan for lunch",
    "Show me high-protein, low-fat products",
    "What are my options for vegan breakfast?",
  ],
  coordinator: [
    "Help me plan a week of meals",
    "I need products for 50 people",
    "What's the best way to save money?",
    "Show me balanced nutrition options",
  ],
  budget: [
    "What are your cheapest bulk options?",
    "Find me the best deals this week",
    "Show me cost per serving for pasta",
    "How much can I save buying in bulk?",
  ],
  nutrition: [
    "I need high-protein meal options",
    "Show me low-calorie products",
    "What are good sources of healthy fats?",
    "Find balanced meals under 500 calories",
  ],
  dietary: [
    "I need dairy-free alternatives",
    "Show me gluten-free options",
    "Find vegan protein sources",
    "What products are nut-free?",
  ],
  'meal-planning': [
    "Create a vegetarian lunch menu",
    "Plan breakfast for 30 people",
    "Show me complete dinner recipes",
    "I need ingredients for pasta dishes",
  ],
};

export const MOCK_MEALS: Meal[] = [
  {
    id: 'meal-1',
    name: 'Veggie-Schnitzel auf Weizenbasis',
    description: 'Crispy vegetarian schnitzel on wheat basis',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1600803907087-f56d462fd26b?w=400&h=300&fit=crop',
    components: ['Veggie-Schnitzel', 'Soße "Balkan Art"'],
    allergens: ['gluten', 'soy'],
    nutritionalInfo: {
      calories: 420,
      protein: 18,
      carbs: 48,
      fat: 16,
    },
    dietaryTags: ['Vegetarian'],
    price: 6.50,
    servingSize: '350g',
  },
  {
    id: 'meal-2',
    name: 'Grüne Bohnen "naturell"',
    description: 'Natural green beans, lightly seasoned',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&h=300&fit=crop',
    components: ['Grüne Bohnen'],
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 3,
      carbs: 12,
      fat: 0.5,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.20,
    servingSize: '200g',
  },
  {
    id: 'meal-3',
    name: 'Salzkartoffel',
    description: 'Classic boiled potatoes with salt',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop',
    components: ['Salzkartoffel'],
    allergens: [],
    nutritionalInfo: {
      calories: 180,
      protein: 4,
      carbs: 38,
      fat: 0.2,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 2.80,
    servingSize: '250g',
  },
  {
    id: 'meal-4',
    name: 'Veggie-Frikassee "Frühlings Art"',
    description: 'Spring-style vegetarian fricassee with vegetables in cream sauce',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    components: [
      'Geschnetzeltes auf Erbsen- und Weizenbasis',
      'Helle Gemüsesoße mit Erbsen',
      'Möhren und Champignons',
    ],
    allergens: ['gluten', 'dairy', 'soy'],
    nutritionalInfo: {
      calories: 385,
      protein: 16,
      carbs: 42,
      fat: 18,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.20,
    servingSize: '400g',
  },
  {
    id: 'meal-5',
    name: 'Fingermöhren "naturell"',
    description: 'Natural baby carrots, tender and sweet',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop',
    components: ['Fingermöhren'],
    allergens: [],
    nutritionalInfo: {
      calories: 55,
      protein: 1.2,
      carbs: 11,
      fat: 0.3,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.50,
    servingSize: '200g',
  },
  {
    id: 'meal-6',
    name: 'Naturreis',
    description: 'Wholesome natural brown rice',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    components: ['Naturreis'],
    allergens: [],
    nutritionalInfo: {
      calories: 215,
      protein: 5,
      carbs: 45,
      fat: 1.8,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.00,
    servingSize: '200g',
  },
  {
    id: 'meal-7',
    name: 'Bunter Spitzkohl-Gemüsetopf "vegetarisch"',
    description: 'Colorful pointed cabbage vegetable stew',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1547928576-4a5a5c7781ef?w=400&h=300&fit=crop',
    components: ['Bunter Spitzkohl', 'Gemüse-Mix'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 38,
      fat: 14,
    },
    dietaryTags: ['Vegetarian'],
    price: 6.80,
    servingSize: '380g',
  },
  {
    id: 'meal-8',
    name: 'Vollkornbrötchen',
    description: 'Hearty whole grain rolls',
    category: 'Bread',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    components: ['Vollkornbrötchen'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 245,
      protein: 8,
      carbs: 48,
      fat: 2.5,
    },
    dietaryTags: ['Vegetarian'],
    price: 1.50,
    servingSize: '80g',
  },
  {
    id: 'meal-9',
    name: 'Joghurt mit Früchten',
    description: 'Creamy yogurt with fresh fruits',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
    components: ['Joghurt', 'Früchte'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 180,
      protein: 6,
      carbs: 28,
      fat: 4.5,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 2.50,
    servingSize: '150g',
  },
  {
    id: 'meal-10',
    name: 'Pumpkin Pasta',
    description: 'Tortellini in butternut squash sauce with quinoa vegetables',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    components: [
      'Tortellini in Butternut-Kürbissoße',
      'Mit Rucola Kürbiskernen',
      'Quinoa verfeinert',
    ],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 465,
      protein: 18,
      carbs: 58,
      fat: 19,
    },
    dietaryTags: ['Vegetarian'],
    price: 8.50,
    servingSize: '420g',
  },
  {
    id: 'meal-11',
    name: 'Salat',
    description: 'Fresh mixed salad',
    category: 'Salad',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    components: ['Gemischter Salat'],
    allergens: [],
    nutritionalInfo: {
      calories: 45,
      protein: 2,
      carbs: 8,
      fat: 0.5,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.80,
    servingSize: '150g',
  },
  {
    id: 'meal-12',
    name: 'Herzhafter Michel',
    description: 'Hearty casserole with broccoli, tomato and onions with cheese topping',
    category: 'Main',
    imageUrl: 'https://images.unsplash.com/photo-1604908815875-6d0e27bf6d0e?w=400&h=300&fit=crop',
    components: [
      'Brotauflauf mit Brokkoli',
      'Tomate und Zwiebeln',
      'Mit Käse überbacken',
    ],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 520,
      protein: 24,
      carbs: 52,
      fat: 24,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.80,
    servingSize: '450g',
  },
  {
    id: 'meal-13',
    name: 'Obst der Saison',
    description: 'Fresh seasonal fruit',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    components: ['Obst der Saison'],
    allergens: [],
    nutritionalInfo: {
      calories: 85,
      protein: 1,
      carbs: 20,
      fat: 0.3,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 2.80,
    servingSize: '150g',
  },
  {
    id: 'meal-14',
    name: 'Hähnchenbrust-Geschnetzeltes',
    description: 'Sliced chicken breast in creamy sauce',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    components: ['Hähnchenbrust', 'Cremige Soße'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 385,
      protein: 32,
      carbs: 12,
      fat: 24,
    },
    dietaryTags: ['Gluten-Free'],
    price: 9.20,
    servingSize: '350g',
  },
  {
    id: 'meal-15',
    name: 'Lachsfilet mit Kräuterkruste',
    description: 'Salmon fillet with herb crust',
    category: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    components: ['Lachsfilet', 'Kräuterkruste'],
    allergens: ['fish', 'gluten'],
    nutritionalInfo: {
      calories: 420,
      protein: 38,
      carbs: 8,
      fat: 26,
    },
    dietaryTags: ['Pescatarian'],
    price: 12.50,
    servingSize: '280g',
  },
  {
    id: 'meal-16',
    name: 'Rinderbraten mit Rotkohl',
    description: 'Roast beef with red cabbage',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=300&fit=crop',
    components: ['Rinderbraten', 'Rotkohl', 'Soße'],
    allergens: [],
    nutritionalInfo: {
      calories: 485,
      protein: 42,
      carbs: 18,
      fat: 28,
    },
    dietaryTags: ['Gluten-Free'],
    price: 10.80,
    servingSize: '400g',
  },
  {
    id: 'meal-17',
    name: 'Kartoffelpüree',
    description: 'Creamy mashed potatoes',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1585232351592-856a2f2c4df3?w=400&h=300&fit=crop',
    components: ['Kartoffelpüree'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 195,
      protein: 4,
      carbs: 32,
      fat: 6,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 3.20,
    servingSize: '250g',
  },
  {
    id: 'meal-18',
    name: 'Gemischtes Gemüse',
    description: 'Mixed vegetables medley',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    components: ['Karotten', 'Brokkoli', 'Blumenkohl'],
    allergens: [],
    nutritionalInfo: {
      calories: 75,
      protein: 3.5,
      carbs: 14,
      fat: 0.8,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.50,
    servingSize: '200g',
  },
  {
    id: 'meal-19',
    name: 'Spätzle',
    description: 'Traditional German egg noodles',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1612874292776-d399be7e8bdc?w=400&h=300&fit=crop',
    components: ['Spätzle'],
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 285,
      protein: 9,
      carbs: 52,
      fat: 4,
    },
    dietaryTags: ['Vegetarian'],
    price: 3.80,
    servingSize: '250g',
  },
  {
    id: 'meal-20',
    name: 'Tiramisu',
    description: 'Classic Italian dessert',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
    components: ['Mascarpone', 'Espresso', 'Löffelbiskuit'],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 7,
      carbs: 42,
      fat: 20,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.50,
    servingSize: '150g',
  },
];
