import { Product, Meal, OrganizationProfile, OrderHistory } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'APT-001',
    name: 'Pork Roast with Gravy',
    description: 'Tender pork roast with rich gravy, a classic German favorite',
    category: 'Meat Dishes',
    price: 8.50,
    bulkPrice: 7.20,
    bulkMinQuantity: 10,
    unit: 'per portion (350g)',
    imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 420,
      protein: 32,
      carbs: 8,
      fat: 28,
      fiber: 1,
      sugar: 2,
      salt: 1.2,
      saturatedFat: 10,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 3.2,
      regionalSourcing: true,
      sustainabilityScore: 65,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 180,
    },
    foodSafety: {
      certifications: ['IFS', 'ISO22000', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT001-2024-11-15',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: '2',
    sku: 'APT-002',
    name: 'Breaded Chicken Schnitzel',
    description: 'Breaded chicken schnitzel, crispy and golden',
    category: 'Poultry',
    price: 7.80,
    bulkPrice: 6.50,
    bulkMinQuantity: 12,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 28,
      carbs: 24,
      fat: 20,
      fiber: 2,
      sugar: 1,
      salt: 1.1,
      saturatedFat: 4,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.1,
      regionalSourcing: true,
      sustainabilityScore: 72,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 150,
    },
    foodSafety: {
      certifications: ['IFS', 'BRC', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT002-2024-11-18',
      storageConditions: 'Store at -18°C. Cook from frozen at 180°C for 20 minutes.',
    },
  },
  {
    id: '3',
    sku: 'APT-003',
    name: 'Mashed Potatoes',
    description: 'Creamy mashed potatoes, smooth and delicious',
    category: 'Sides',
    price: 3.20,
    bulkPrice: 2.80,
    bulkMinQuantity: 15,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1585232351592-856a2f2c4df3?w=400&h=300&fit=crop',
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 195,
      protein: 4,
      carbs: 32,
      fat: 6,
      fiber: 3,
      sugar: 2,
      salt: 0.9,
      saturatedFat: 3.5,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.25,
      regionalSourcing: true,
      sustainabilityScore: 88,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 100,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT003-2024-11-20',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: '4',
    sku: 'APT-004',
    name: 'Red Cabbage',
    description: 'Traditional German red cabbage with apples and spices',
    category: 'Vegetables',
    price: 3.50,
    bulkPrice: 3.00,
    bulkMinQuantity: 10,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 85,
      protein: 2,
      carbs: 18,
      fat: 0.5,
      fiber: 4,
      sugar: 12,
      salt: 0.6,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Recyclable pouch',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 120,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT004-2024-11-12',
      storageConditions: 'Store at -18°C or below. Can be heated from frozen.',
    },
  },
  {
    id: '5',
    sku: 'APT-005',
    name: 'Spätzle',
    description: 'Traditional Swabian egg noodles',
    category: 'Sides',
    price: 3.80,
    bulkPrice: 3.20,
    bulkMinQuantity: 12,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1612874292776-d399be7e8bdc?w=400&h=300&fit=crop',
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 285,
      protein: 9,
      carbs: 52,
      fat: 4,
      fiber: 2,
      sugar: 1,
      salt: 0.7,
      saturatedFat: 1.2,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.32,
      regionalSourcing: true,
      sustainabilityScore: 80,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 55,
      },
      transportDistance: 140,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT005-2024-11-19',
      storageConditions: 'Keep frozen at -18°C. Reheat in boiling water or microwave.',
    },
  },
  {
    id: '6',
    sku: 'APT-006',
    name: 'Beef Roulade',
    description: 'Beef roulade with bacon, pickles and mustard',
    category: 'Meat Dishes',
    price: 9.50,
    bulkPrice: 8.20,
    bulkMinQuantity: 8,
    unit: 'per portion (300g)',
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 485,
      protein: 38,
      carbs: 6,
      fat: 34,
      fiber: 1,
      sugar: 2,
      salt: 1.8,
      saturatedFat: 14,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 4.2,
      regionalSourcing: true,
      sustainabilityScore: 58,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 200,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT006-2024-11-14',
      storageConditions: 'Keep frozen at -18°C. Heat thoroughly to 75°C.',
    },
  },
  {
    id: '7',
    sku: 'APT-007',
    name: 'Pollock Fillet with Butter Sauce',
    description: 'Pollock fillet with delicate butter sauce',
    category: 'Fish',
    price: 8.20,
    bulkPrice: 7.00,
    bulkMinQuantity: 10,
    unit: 'per portion (180g)',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    allergens: ['fish', 'dairy'],
    nutritionalInfo: {
      calories: 245,
      protein: 28,
      carbs: 2,
      fat: 14,
      fiber: 0,
      sugar: 1,
      salt: 0.9,
      saturatedFat: 6,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 1.8,
      regionalSourcing: false,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 50,
      },
      transportDistance: 850,
    },
    foodSafety: {
      certifications: ['IFS', 'BRC', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT007-2024-11-16',
      storageConditions: 'Keep frozen at -18°C. Do not refreeze after thawing.',
    },
  },
  {
    id: '8',
    sku: 'APT-008',
    name: 'Green Beans',
    description: 'Fresh green beans, lightly seasoned',
    category: 'Vegetables',
    price: 3.20,
    bulkPrice: 2.70,
    bulkMinQuantity: 15,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 3,
      carbs: 12,
      fat: 0.5,
      fiber: 4,
      sugar: 3,
      salt: 0.3,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 95,
      packaging: {
        type: 'Recyclable plastic bag',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 120,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'EUOrganic'],
      euNutritionLabel: true,
      traceabilityCode: 'APT008-2024-11-18',
      storageConditions: 'Store at -18°C. Cook from frozen.',
    },
  },
  {
    id: '9',
    sku: 'APT-009',
    name: 'Boiled Potatoes',
    description: 'Classic boiled potatoes with salt',
    category: 'Sides',
    price: 2.80,
    bulkPrice: 2.40,
    bulkMinQuantity: 20,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 180,
      protein: 4,
      carbs: 38,
      fat: 0.2,
      fiber: 3,
      sugar: 1,
      salt: 0.8,
      saturatedFat: 0.05,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.12,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 40,
      },
      transportDistance: 80,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT009-2024-11-21',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: '10',
    sku: 'APT-010',
    name: 'Roast Gravy',
    description: 'Rich, savory gravy perfect for meat dishes',
    category: 'Sauces',
    price: 12.50,
    bulkPrice: 10.80,
    bulkMinQuantity: 8,
    unit: '1L container',
    imageUrl: 'https://images.unsplash.com/photo-1605521560596-83f6afe9d2d2?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 2,
      carbs: 8,
      fat: 3,
      fiber: 0.5,
      sugar: 2,
      salt: 1.2,
      saturatedFat: 1.5,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.28,
      regionalSourcing: true,
      sustainabilityScore: 78,
      packaging: {
        type: 'Recyclable plastic bottle',
        recyclable: true,
        recycledContent: 55,
      },
      transportDistance: 160,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT010-2024-11-10',
      storageConditions: 'Refrigerate after opening. Use within 5 days.',
    },
  },
  {
    id: '11',
    sku: 'APT-011',
    name: 'Mixed Vegetables',
    description: 'Mixed vegetables with carrots, broccoli, and cauliflower',
    category: 'Vegetables',
    price: 3.50,
    bulkPrice: 3.00,
    bulkMinQuantity: 12,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 75,
      protein: 3.5,
      carbs: 14,
      fat: 0.8,
      fiber: 5,
      sugar: 4,
      salt: 0.4,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.18,
      regionalSourcing: true,
      sustainabilityScore: 90,
      packaging: {
        type: 'PE plastic bag (recyclable)',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 150,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT011-2024-11-17',
      storageConditions: 'Store at -18°C or below. Can be cooked from frozen.',
    },
  },
  {
    id: '12',
    sku: 'APT-012',
    name: 'Königsberg Meatballs',
    description: 'Traditional meatballs in creamy caper sauce',
    category: 'Meat Dishes',
    price: 8.80,
    bulkPrice: 7.50,
    bulkMinQuantity: 10,
    unit: 'per portion (380g)',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',
    allergens: ['eggs', 'dairy'],
    nutritionalInfo: {
      calories: 425,
      protein: 26,
      carbs: 18,
      fat: 28,
      fiber: 1,
      sugar: 3,
      salt: 1.5,
      saturatedFat: 12,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.8,
      regionalSourcing: true,
      sustainabilityScore: 68,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 170,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT012-2024-11-13',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: '13',
    sku: 'APT-013',
    name: 'Thai Red Curry with Chicken',
    description: 'Authentic Thai red curry with tender chicken, bamboo shoots, and basil in coconut peanut sauce',
    category: 'International',
    price: 8.50,
    bulkPrice: 7.30,
    bulkMinQuantity: 10,
    unit: 'per portion (350g)',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 465,
      protein: 28,
      carbs: 24,
      fat: 28,
      fiber: 3,
      sugar: 8,
      salt: 1.4,
      saturatedFat: 16,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.4,
      regionalSourcing: false,
      sustainabilityScore: 68,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 350,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT013-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: '14',
    sku: 'APT-014',
    name: 'Thai Green Curry with Vegetables',
    description: 'Fragrant green curry with mixed vegetables, Thai basil, and creamy cashew-coconut sauce',
    category: 'International',
    price: 7.80,
    bulkPrice: 6.80,
    bulkMinQuantity: 12,
    unit: 'per portion (350g)',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 395,
      protein: 12,
      carbs: 32,
      fat: 24,
      fiber: 6,
      sugar: 9,
      salt: 1.2,
      saturatedFat: 14,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 1.2,
      regionalSourcing: false,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 320,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT014-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Microwave or stovetop reheat.',
    },
  },
  {
    id: '15',
    sku: 'APT-015',
    name: 'Thai Massaman Curry with Beef',
    description: 'Rich and mild massaman curry with tender beef, potatoes, and roasted peanuts',
    category: 'International',
    price: 9.20,
    bulkPrice: 7.90,
    bulkMinQuantity: 10,
    unit: 'per portion (380g)',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 525,
      protein: 32,
      carbs: 28,
      fat: 32,
      fiber: 4,
      sugar: 7,
      salt: 1.3,
      saturatedFat: 18,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 3.8,
      regionalSourcing: false,
      sustainabilityScore: 62,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 340,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000', 'Halal'],
      euNutritionLabel: true,
      traceabilityCode: 'APT015-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: '16',
    sku: 'APT-016',
    name: 'Thai Panang Curry with Shrimp',
    description: 'Creamy panang curry with succulent shrimp, kaffir lime, and ground peanuts',
    category: 'International',
    price: 9.80,
    bulkPrice: 8.50,
    bulkMinQuantity: 8,
    unit: 'per portion (320g)',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    allergens: ['nuts', 'shellfish'],
    nutritionalInfo: {
      calories: 445,
      protein: 26,
      carbs: 22,
      fat: 28,
      fiber: 2,
      sugar: 6,
      salt: 1.6,
      saturatedFat: 15,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.8,
      regionalSourcing: false,
      sustainabilityScore: 64,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 380,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT016-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Do not refreeze after thawing.',
    },
  },
  {
    id: '17',
    sku: 'APT-017',
    name: 'Jasmine Rice',
    description: 'Fragrant Thai jasmine rice, steamed to perfection',
    category: 'Sides',
    price: 2.50,
    bulkPrice: 2.10,
    bulkMinQuantity: 20,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 205,
      protein: 4,
      carbs: 45,
      fat: 0.4,
      fiber: 1,
      sugar: 0,
      salt: 0.1,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.8,
      regionalSourcing: false,
      sustainabilityScore: 70,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 50,
      },
      transportDistance: 8500,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT017-2024-11-22',
      storageConditions: 'Keep frozen. Microwave or steam reheat.',
    },
  },
];

export const ALLERGEN_LABELS: Record<string, { label: string; color: string }> = {
  nuts: { label: 'Nuts', color: 'bg-destructive text-destructive-foreground' },
  dairy: { label: 'Dairy', color: 'bg-warning text-warning-foreground' },
  gluten: { label: 'Gluten', color: 'bg-warning text-warning-foreground' },
  eggs: { label: 'Eggs', color: 'bg-warning text-warning-foreground' },
  soy: { label: 'Soy', color: 'bg-muted text-muted-foreground' },
  fish: { label: 'Fish', color: 'bg-destructive text-destructive-foreground' },
  shellfish: { label: 'Shellfish', color: 'bg-destructive text-destructive-foreground' },
  sesame: { label: 'Sesame', color: 'bg-muted text-muted-foreground' },
};

export const CONVERSATION_STARTERS = [
  "Find me budget-friendly protein options",
  "I need a gluten-free meal plan for lunch",
  "Show me high-protein, low-fat products",
  "What are my options for vegan breakfast?",
];

export const AGENT_CONVERSATION_STARTERS: Record<string, string[]> = {
  auto: [
    "Find me budget-friendly protein options",
    "I need a gluten-free meal plan for lunch",
    "Show me high-protein, low-fat products",
    "What are my options for vegan breakfast?",
  ],
  coordinator: [
    "Help me plan a week of meals",
    "I need products for 50 people",
    "What's the best way to save money?",
    "Show me balanced nutrition options",
  ],
  budget: [
    "What are your cheapest bulk options?",
    "Find me the best deals this week",
    "Show me cost per serving for pasta",
    "How much can I save buying in bulk?",
  ],
  nutrition: [
    "I need high-protein meal options",
    "Show me low-calorie products",
    "What are good sources of healthy fats?",
    "Find balanced meals under 500 calories",
  ],
  dietary: [
    "I need dairy-free alternatives",
    "Show me gluten-free options",
    "Find vegan protein sources",
    "What products are nut-free?",
  ],
  'meal-planning': [
    "Create a vegetarian lunch menu",
    "Plan breakfast for 30 people",
    "Show me complete dinner recipes",
    "I need ingredients for pasta dishes",
  ],
};

export const MOCK_ORDER_HISTORY: OrderHistory[] = [
  {
    id: 'order-001',
    date: Date.now() - 30 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[0],
        quantity: 10,
      },
      {
        product: MOCK_PRODUCTS[1],
        quantity: 12,
      },
      {
        product: MOCK_PRODUCTS[6],
        quantity: 5,
      },
    ],
    total: 1289.90,
    status: 'completed',
  },
  {
    id: 'order-002',
    date: Date.now() - 15 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[8],
        quantity: 15,
      },
      {
        product: MOCK_PRODUCTS[10],
        quantity: 8,
      },
      {
        product: MOCK_PRODUCTS[4],
        quantity: 4,
      },
    ],
    total: 746.00,
    status: 'completed',
  },
  {
    id: 'order-003',
    date: Date.now() - 7 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[2],
        quantity: 6,
      },
      {
        product: MOCK_PRODUCTS[11],
        quantity: 6,
      },
    ],
    total: 420.00,
    status: 'completed',
  },
];

export const MOCK_ORGANIZATION_PROFILE: OrganizationProfile = {
  id: 'org-001',
  name: "St. Mary's Regional Hospital",
  type: 'hospital',
  contactEmail: 'procurement@stmarys-hospital.com',
  contactPhone: '+1 (555) 234-5678',
  address: '1234 Healthcare Drive, Medical District, CA 90210',
  servingCapacity: 450,
  preferences: {
    dietaryRestrictions: ['vegetarian'],
    allergenExclusions: ['nuts', 'shellfish'],
    budgetPerServing: 3.75,
    specialRequirements: 'Halal certification required for all meat products. Prefer organic produce when available. Must meet hospital dietary standards for patient meals.',
    dietaryEnforcement: {
      requireVegetarianDaily: true,
      requireVeganDaily: false,
      minimumVegetarianPerWeek: 7,
      minimumVeganPerWeek: 0,
    },
  },
  orderHistory: MOCK_ORDER_HISTORY,
  createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
  updatedAt: Date.now(),
};

export const MOCK_MEALS: Meal[] = [
  {
    id: 'meal-1',
    name: 'Traditional Fish and Chips',
    description: 'Beer-battered cod with crispy chips and mushy peas',
    category: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?w=400&h=300&fit=crop',
    components: ['Battered Cod Fillet', 'Crispy Chips', 'Mushy Peas', 'Tartar Sauce'],
    allergens: ['fish', 'gluten'],
    nutritionalInfo: {
      calories: 685,
      protein: 38,
      carbs: 72,
      fat: 26,
      fiber: 6,
      sugar: 2,
      salt: 1.4,
      saturatedFat: 3.5,
    },
    dietaryTags: ['Pescatarian'],
    price: 8.50,
    servingSize: '450g',
    sustainability: {
      co2Footprint: 1.8,
      regionalSourcing: true,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 180,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL001-2024-11-20',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: 'meal-2',
    name: 'Shepherd\'s Pie',
    description: 'Classic minced lamb with vegetables topped with creamy mashed potato',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',
    components: ['Minced Lamb', 'Mixed Vegetables', 'Mashed Potato Topping', 'Rich Gravy'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 525,
      protein: 28,
      carbs: 45,
      fat: 24,
      fiber: 5,
      sugar: 4,
      salt: 1.2,
      saturatedFat: 10,
    },
    dietaryTags: ['Gluten-Free'],
    price: 7.80,
    servingSize: '400g',
    sustainability: {
      co2Footprint: 3.5,
      regionalSourcing: true,
      sustainabilityScore: 68,
      packaging: {
        type: 'Recyclable plastic film',
        recyclable: true,
        recycledContent: 50,
      },
      transportDistance: 120,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL002-2024-11-18',
      storageConditions: 'Store at -18°C or below. Cook from frozen.',
    },
  },
  {
    id: 'meal-3',
    name: 'Roast Chicken with Yorkshire Pudding',
    description: 'Tender roast chicken with traditional Yorkshire pudding and roast vegetables',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    components: ['Roast Chicken', 'Yorkshire Pudding', 'Roast Potatoes', 'Seasonal Veg', 'Gravy'],
    allergens: ['gluten', 'eggs', 'dairy'],
    nutritionalInfo: {
      calories: 595,
      protein: 42,
      carbs: 52,
      fat: 22,
      fiber: 5,
      sugar: 3,
      salt: 1.3,
      saturatedFat: 6,
    },
    dietaryTags: [],
    price: 9.20,
    servingSize: '450g',
    sustainability: {
      co2Footprint: 2.8,
      regionalSourcing: true,
      sustainabilityScore: 72,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 85,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL003-2024-11-21',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: 'meal-4',
    name: 'Bangers and Mash',
    description: 'Traditional pork sausages with creamy mashed potato and onion gravy',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',
    components: ['Pork Sausages', 'Mashed Potatoes', 'Onion Gravy', 'Garden Peas'],
    allergens: ['dairy', 'gluten'],
    nutritionalInfo: {
      calories: 615,
      protein: 24,
      carbs: 48,
      fat: 36,
      fiber: 4,
      sugar: 4,
      salt: 1.6,
      saturatedFat: 14,
    },
    dietaryTags: [],
    price: 6.80,
    servingSize: '420g',
    sustainability: {
      co2Footprint: 3.2,
      regionalSourcing: true,
      sustainabilityScore: 65,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 95,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'BRC'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL004-2024-11-19',
      storageConditions: 'Store frozen. Cook thoroughly to 75°C.',
    },
  },
  {
    id: 'meal-5',
    name: 'Beef and Ale Pie',
    description: 'Slow-cooked beef in rich ale gravy with flaky pastry',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1619895092538-128341789043?w=400&h=300&fit=crop',
    components: ['Beef Chunks', 'Ale Gravy', 'Shortcrust Pastry', 'Root Vegetables'],
    allergens: ['gluten', 'dairy'],
    nutritionalInfo: {
      calories: 685,
      protein: 32,
      carbs: 58,
      fat: 36,
      fiber: 4,
      sugar: 5,
      salt: 1.5,
      saturatedFat: 16,
    },
    dietaryTags: [],
    price: 9.50,
    servingSize: '450g',
    sustainability: {
      co2Footprint: 4.2,
      regionalSourcing: true,
      sustainabilityScore: 62,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 125,
    },
    foodSafety: {
      certifications: ['IFS', 'ISO22000', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL005-2024-11-20',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C.',
    },
  },
  {
    id: 'meal-6',
    name: 'Cottage Pie',
    description: 'Minced beef with vegetables topped with golden mashed potato',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',
    components: ['Minced Beef', 'Mixed Vegetables', 'Mashed Potato', 'Rich Gravy'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 535,
      protein: 29,
      carbs: 46,
      fat: 24,
      fiber: 5,
      sugar: 4,
      salt: 1.3,
      saturatedFat: 10,
    },
    dietaryTags: ['Gluten-Free'],
    price: 7.50,
    servingSize: '400g',
    sustainability: {
      co2Footprint: 3.8,
      regionalSourcing: true,
      sustainabilityScore: 68,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 110,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL006-2024-11-18',
      storageConditions: 'Store frozen. Reheat thoroughly.',
    },
  },
  {
    id: 'meal-7',
    name: 'Toad in the Hole',
    description: 'Pork sausages baked in Yorkshire pudding batter with onion gravy',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1618640843175-b6766b5f46e6?w=400&h=300&fit=crop',
    components: ['Pork Sausages', 'Yorkshire Pudding Batter', 'Onion Gravy'],
    allergens: ['gluten', 'eggs', 'dairy'],
    nutritionalInfo: {
      calories: 625,
      protein: 26,
      carbs: 54,
      fat: 34,
      fiber: 3,
      sugar: 5,
      salt: 1.7,
      saturatedFat: 12,
    },
    dietaryTags: [],
    price: 7.20,
    servingSize: '420g',
    sustainability: {
      co2Footprint: 3.1,
      regionalSourcing: true,
      sustainabilityScore: 66,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 100,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL007-2024-11-21',
      storageConditions: 'Store frozen. Cook thoroughly.',
    },
  },
  {
    id: 'meal-8',
    name: 'Lancashire Hotpot',
    description: 'Tender lamb with sliced potatoes and vegetables in rich gravy',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1605329230155-a0e0bdda5d38?w=400&h=300&fit=crop',
    components: ['Lamb Chunks', 'Sliced Potatoes', 'Carrots', 'Onions', 'Lamb Gravy'],
    allergens: [],
    nutritionalInfo: {
      calories: 565,
      protein: 32,
      carbs: 45,
      fat: 28,
      fiber: 5,
      sugar: 4,
      salt: 1.4,
      saturatedFat: 12,
    },
    dietaryTags: ['Gluten-Free', 'Dairy-Free'],
    price: 8.80,
    servingSize: '450g',
    sustainability: {
      co2Footprint: 4.0,
      regionalSourcing: true,
      sustainabilityScore: 64,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 130,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'BRC'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL008-2024-11-20',
      storageConditions: 'Keep frozen. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: 'meal-9',
    name: 'Chicken and Mushroom Pie',
    description: 'Chicken breast in creamy mushroom sauce with puff pastry',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1619895092538-128341789043?w=400&h=300&fit=crop',
    components: ['Chicken Breast', 'Mushrooms', 'Cream Sauce', 'Puff Pastry'],
    allergens: ['gluten', 'dairy'],
    nutritionalInfo: {
      calories: 545,
      protein: 28,
      carbs: 42,
      fat: 28,
      fiber: 3,
      sugar: 3,
      salt: 1.2,
      saturatedFat: 14,
    },
    dietaryTags: [],
    price: 8.50,
    servingSize: '400g',
    sustainability: {
      co2Footprint: 2.4,
      regionalSourcing: true,
      sustainabilityScore: 71,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 90,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL009-2024-11-19',
      storageConditions: 'Keep frozen. Cook to 75°C.',
    },
  },
  {
    id: 'meal-10',
    name: 'Ploughman\'s Lunch',
    description: 'Traditional British cheese plate with pickles, crusty bread and salad',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400&h=300&fit=crop',
    components: ['Cheddar Cheese', 'Pickled Onions', 'Branston Pickle', 'Crusty Bread', 'Mixed Salad'],
    allergens: ['gluten', 'dairy'],
    nutritionalInfo: {
      calories: 485,
      protein: 22,
      carbs: 48,
      fat: 22,
      fiber: 6,
      sugar: 8,
      salt: 2.1,
      saturatedFat: 12,
    },
    dietaryTags: ['Vegetarian'],
    price: 6.50,
    servingSize: '350g',
    sustainability: {
      co2Footprint: 1.2,
      regionalSourcing: true,
      sustainabilityScore: 82,
      packaging: {
        type: 'Recyclable plastic tray',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 75,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL010-2024-11-21',
      storageConditions: 'Keep refrigerated. Consume within 3 days.',
    },
  },
  {
    id: 'meal-11',
    name: 'Jacket Potato with Baked Beans',
    description: 'Fluffy baked potato with traditional baked beans and cheese',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1615830941177-b2d18071dd8c?w=400&h=300&fit=crop',
    components: ['Baked Potato', 'Baked Beans', 'Cheddar Cheese', 'Butter'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 425,
      protein: 18,
      carbs: 65,
      fat: 12,
      fiber: 12,
      sugar: 8,
      salt: 1.4,
      saturatedFat: 7,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 4.80,
    servingSize: '400g',
    sustainability: {
      co2Footprint: 0.4,
      regionalSourcing: true,
      sustainabilityScore: 88,
      packaging: {
        type: 'Recyclable cardboard',
        recyclable: true,
        recycledContent: 80,
      },
      transportDistance: 60,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL011-2024-11-20',
      storageConditions: 'Store frozen. Microwave or oven reheat.',
    },
  },
  {
    id: 'meal-12',
    name: 'Full English Breakfast',
    description: 'Traditional full English with sausage, bacon, eggs, beans, tomato and toast',
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop',
    components: ['Pork Sausages', 'Bacon', 'Fried Eggs', 'Baked Beans', 'Grilled Tomato', 'Toast'],
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 785,
      protein: 38,
      carbs: 52,
      fat: 46,
      fiber: 8,
      sugar: 9,
      salt: 2.3,
      saturatedFat: 16,
    },
    dietaryTags: [],
    price: 7.50,
    servingSize: '500g',
    sustainability: {
      co2Footprint: 3.8,
      regionalSourcing: true,
      sustainabilityScore: 58,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 105,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'BRC'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL012-2024-11-19',
      storageConditions: 'Keep frozen. Cook all components thoroughly.',
    },
  },
  {
    id: 'meal-13',
    name: 'Steak and Kidney Pudding',
    description: 'Traditional steamed suet pudding filled with beef and kidney in rich gravy',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    components: ['Beef Chunks', 'Kidney', 'Suet Pastry', 'Rich Gravy'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 725,
      protein: 36,
      carbs: 48,
      fat: 42,
      fiber: 3,
      sugar: 3,
      salt: 1.6,
      saturatedFat: 20,
    },
    dietaryTags: [],
    price: 9.80,
    servingSize: '450g',
    sustainability: {
      co2Footprint: 4.5,
      regionalSourcing: true,
      sustainabilityScore: 60,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 115,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL013-2024-11-20',
      storageConditions: 'Keep frozen. Steam or oven cook to 75°C.',
    },
  },
  {
    id: 'meal-14',
    name: 'Coronation Chicken',
    description: 'Chicken in mild curry mayonnaise sauce with rice and salad',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    components: ['Chicken Breast', 'Curry Mayonnaise', 'Basmati Rice', 'Mixed Salad'],
    allergens: ['eggs', 'dairy'],
    nutritionalInfo: {
      calories: 465,
      protein: 32,
      carbs: 42,
      fat: 18,
      fiber: 3,
      sugar: 6,
      salt: 1.0,
      saturatedFat: 4,
    },
    dietaryTags: ['Gluten-Free'],
    price: 7.80,
    servingSize: '380g',
    sustainability: {
      co2Footprint: 2.2,
      regionalSourcing: true,
      sustainabilityScore: 74,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 95,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL014-2024-11-21',
      storageConditions: 'Keep chilled. Use within 2 days.',
    },
  },
  {
    id: 'meal-15',
    name: 'Beef Wellington',
    description: 'Beef fillet wrapped in mushroom duxelles and puff pastry',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=300&fit=crop',
    components: ['Beef Fillet', 'Mushroom Duxelles', 'Puff Pastry', 'Red Wine Jus'],
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 825,
      protein: 42,
      carbs: 38,
      fat: 52,
      fiber: 3,
      sugar: 2,
      salt: 1.5,
      saturatedFat: 24,
    },
    dietaryTags: [],
    price: 14.50,
    servingSize: '400g',
    sustainability: {
      co2Footprint: 5.2,
      regionalSourcing: true,
      sustainabilityScore: 56,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 140,
    },
    foodSafety: {
      certifications: ['IFS', 'ISO22000', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL015-2024-11-19',
      storageConditions: 'Keep frozen. Cook to medium-rare 52°C.',
    },
  },
  {
    id: 'meal-16',
    name: 'Mushy Peas',
    description: 'Traditional British mushy peas',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1570544820299-f92c97c2ceda?w=400&h=300&fit=crop',
    components: ['Marrowfat Peas', 'Butter', 'Mint'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 145,
      protein: 9,
      carbs: 22,
      fat: 2,
      fiber: 8,
      sugar: 3,
      salt: 0.8,
      saturatedFat: 1,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 2.50,
    servingSize: '200g',
    sustainability: {
      co2Footprint: 0.2,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Recyclable can',
        recyclable: true,
        recycledContent: 85,
      },
      transportDistance: 50,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL016-2024-11-20',
      storageConditions: 'Store in cool dry place. Refrigerate after opening.',
    },
  },
  {
    id: 'meal-17',
    name: 'Roast Potatoes',
    description: 'Crispy golden roast potatoes with herbs',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1623944889288-cd147dbb517c?w=400&h=300&fit=crop',
    components: ['Potatoes', 'Vegetable Oil', 'Fresh Herbs'],
    allergens: [],
    nutritionalInfo: {
      calories: 225,
      protein: 3,
      carbs: 38,
      fat: 8,
      fiber: 4,
      sugar: 1,
      salt: 0.6,
      saturatedFat: 1,
    },
    dietaryTags: ['Vegan', 'Gluten-Free', 'Dairy-Free'],
    price: 3.20,
    servingSize: '250g',
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 90,
      packaging: {
        type: 'Recyclable bag',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 45,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL017-2024-11-21',
      storageConditions: 'Keep frozen. Cook from frozen until golden.',
    },
  },
  {
    id: 'meal-18',
    name: 'Bread and Butter Pudding',
    description: 'Traditional warm pudding with custard',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=300&fit=crop',
    components: ['Bread', 'Custard', 'Raisins', 'Butter', 'Nutmeg'],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 10,
      carbs: 58,
      fat: 14,
      fiber: 2,
      sugar: 32,
      salt: 0.6,
      saturatedFat: 8,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.20,
    servingSize: '200g',
    sustainability: {
      co2Footprint: 0.8,
      regionalSourcing: true,
      sustainabilityScore: 76,
      packaging: {
        type: 'Recyclable foil tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 70,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL018-2024-11-20',
      storageConditions: 'Keep frozen. Oven reheat for best results.',
    },
  },
  {
    id: 'meal-19',
    name: 'Sticky Toffee Pudding',
    description: 'Moist sponge cake with toffee sauce and custard',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=300&fit=crop',
    components: ['Date Sponge', 'Toffee Sauce', 'Custard'],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 465,
      protein: 6,
      carbs: 72,
      fat: 18,
      fiber: 2,
      sugar: 48,
      salt: 0.5,
      saturatedFat: 11,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.50,
    servingSize: '180g',
    sustainability: {
      co2Footprint: 0.9,
      regionalSourcing: true,
      sustainabilityScore: 72,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 80,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL019-2024-11-19',
      storageConditions: 'Keep frozen. Microwave for 2 minutes.',
    },
  },
  {
    id: 'meal-20',
    name: 'Apple Crumble with Custard',
    description: 'Warm apple crumble with vanilla custard',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1606313564756-3a2a6a6e8e8e?w=400&h=300&fit=crop',
    components: ['Bramley Apples', 'Crumble Topping', 'Vanilla Custard'],
    allergens: ['gluten', 'dairy'],
    nutritionalInfo: {
      calories: 385,
      protein: 5,
      carbs: 62,
      fat: 14,
      fiber: 4,
      sugar: 36,
      salt: 0.3,
      saturatedFat: 8,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.00,
    servingSize: '200g',
    sustainability: {
      co2Footprint: 0.6,
      regionalSourcing: true,
      sustainabilityScore: 85,
      packaging: {
        type: 'Recyclable foil tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 55,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL020-2024-11-21',
      storageConditions: 'Keep frozen. Oven or microwave reheat.',
    },
  },
  {
    id: 'meal-21',
    name: 'Vegetable Wellington',
    description: 'Mixed vegetables and chestnuts in puff pastry with vegetarian gravy',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1511910849309-0dffb8785146?w=400&h=300&fit=crop',
    components: ['Mixed Vegetables', 'Chestnuts', 'Puff Pastry', 'Vegetarian Gravy'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 485,
      protein: 14,
      carbs: 58,
      fat: 22,
      fiber: 8,
      sugar: 6,
      salt: 1.1,
      saturatedFat: 8,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.50,
    servingSize: '380g',
    sustainability: {
      co2Footprint: 0.7,
      regionalSourcing: true,
      sustainabilityScore: 88,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 80,
      },
      transportDistance: 60,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL021-2024-11-20',
      storageConditions: 'Keep frozen. Cook until pastry is golden.',
    },
  },
  {
    id: 'meal-22',
    name: 'Cauliflower Cheese',
    description: 'Tender cauliflower in rich cheese sauce',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1562843558-6dd1f33af0eb?w=400&h=300&fit=crop',
    components: ['Cauliflower', 'Cheese Sauce', 'Breadcrumb Topping'],
    allergens: ['dairy', 'gluten'],
    nutritionalInfo: {
      calories: 325,
      protein: 16,
      carbs: 24,
      fat: 20,
      fiber: 5,
      sugar: 6,
      salt: 1.3,
      saturatedFat: 12,
    },
    dietaryTags: ['Vegetarian'],
    price: 5.50,
    servingSize: '300g',
    sustainability: {
      co2Footprint: 0.9,
      regionalSourcing: true,
      sustainabilityScore: 82,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 65,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL022-2024-11-19',
      storageConditions: 'Keep frozen. Oven or microwave reheat.',
    },
  },
  {
    id: 'meal-23',
    name: 'Scones with Jam and Clotted Cream',
    description: 'Traditional afternoon tea scones with strawberry jam and clotted cream',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1612182062349-4c7e40bd4eda?w=400&h=300&fit=crop',
    components: ['Scones', 'Strawberry Jam', 'Clotted Cream'],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 6,
      carbs: 52,
      fat: 18,
      fiber: 2,
      sugar: 24,
      salt: 0.8,
      saturatedFat: 11,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.80,
    servingSize: '180g',
    sustainability: {
      co2Footprint: 0.7,
      regionalSourcing: true,
      sustainabilityScore: 78,
      packaging: {
        type: 'Recyclable box',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 70,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL023-2024-11-20',
      storageConditions: 'Keep in cool dry place. Best served warm.',
    },
  },
  {
    id: 'meal-24',
    name: 'Eton Mess',
    description: 'Crushed meringue with strawberries and whipped cream',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
    components: ['Meringue', 'Fresh Strawberries', 'Whipped Cream'],
    allergens: ['dairy', 'eggs'],
    nutritionalInfo: {
      calories: 325,
      protein: 4,
      carbs: 45,
      fat: 16,
      fiber: 2,
      sugar: 42,
      salt: 0.2,
      saturatedFat: 10,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 4.50,
    servingSize: '180g',
    sustainability: {
      co2Footprint: 0.8,
      regionalSourcing: true,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable plastic pot',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 85,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL024-2024-11-21',
      storageConditions: 'Keep chilled. Consume within 24 hours.',
    },
  },
  {
    id: 'meal-25',
    name: 'Thai Red Curry with Chicken and Rice',
    description: 'Authentic Thai red curry with tender chicken in coconut peanut sauce served with jasmine rice',
    category: 'International',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    components: ['Thai Red Curry with Chicken', 'Jasmine Rice', 'Thai Basil', 'Lime Wedge'],
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 670,
      protein: 32,
      carbs: 69,
      fat: 28,
      fiber: 4,
      sugar: 8,
      salt: 1.5,
      saturatedFat: 16,
    },
    dietaryTags: ['Gluten-Free'],
    price: 10.50,
    servingSize: '550g',
    sustainability: {
      co2Footprint: 3.2,
      regionalSourcing: false,
      sustainabilityScore: 69,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 350,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL025-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: 'meal-26',
    name: 'Thai Green Curry with Vegetables and Rice',
    description: 'Fragrant green curry with mixed vegetables and cashews in coconut sauce, served with jasmine rice',
    category: 'International',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    components: ['Thai Green Curry with Vegetables', 'Jasmine Rice', 'Fresh Basil', 'Cashews'],
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 600,
      protein: 16,
      carbs: 77,
      fat: 24,
      fiber: 7,
      sugar: 9,
      salt: 1.3,
      saturatedFat: 14,
    },
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free'],
    price: 9.50,
    servingSize: '550g',
    sustainability: {
      co2Footprint: 2.0,
      regionalSourcing: false,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 320,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL026-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Microwave or stovetop reheat.',
    },
  },
  {
    id: 'meal-27',
    name: 'Thai Massaman Curry with Beef and Rice',
    description: 'Rich massaman curry with tender beef, potatoes and roasted peanuts, served with jasmine rice',
    category: 'International',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    components: ['Thai Massaman Curry with Beef', 'Jasmine Rice', 'Roasted Peanuts', 'Crispy Shallots'],
    allergens: ['nuts'],
    nutritionalInfo: {
      calories: 730,
      protein: 36,
      carbs: 73,
      fat: 32,
      fiber: 5,
      sugar: 7,
      salt: 1.4,
      saturatedFat: 18,
    },
    dietaryTags: ['Gluten-Free', 'Halal'],
    price: 11.00,
    servingSize: '580g',
    sustainability: {
      co2Footprint: 4.6,
      regionalSourcing: false,
      sustainabilityScore: 63,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 340,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000', 'Halal'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL027-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: 'meal-28',
    name: 'Thai Panang Curry with Shrimp and Rice',
    description: 'Creamy panang curry with succulent shrimp and ground peanuts, served with jasmine rice',
    category: 'International',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    components: ['Thai Panang Curry with Shrimp', 'Jasmine Rice', 'Kaffir Lime Leaves', 'Ground Peanuts'],
    allergens: ['nuts', 'shellfish'],
    nutritionalInfo: {
      calories: 650,
      protein: 30,
      carbs: 67,
      fat: 28,
      fiber: 3,
      sugar: 6,
      salt: 1.7,
      saturatedFat: 15,
    },
    dietaryTags: ['Gluten-Free', 'Pescatarian'],
    price: 11.50,
    servingSize: '520g',
    sustainability: {
      co2Footprint: 3.6,
      regionalSourcing: false,
      sustainabilityScore: 65,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 380,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL028-2024-11-22',
      storageConditions: 'Keep frozen at -18°C. Do not refreeze after thawing.',
    },
  },
];
