import { Product, Meal, OrganizationProfile, OrderHistory } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'APT-001',
    name: 'Pork Roast with Gravy',
    description: 'Tender pork roast with rich gravy, a classic German favorite',
    category: 'Meat Dishes',
    price: 8.50,
    bulkPrice: 7.20,
    bulkMinQuantity: 10,
    unit: 'per portion (350g)',
    imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 420,
      protein: 32,
      carbs: 8,
      fat: 28,
      fiber: 1,
      sugar: 2,
      salt: 1.2,
      saturatedFat: 10,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 3.2,
      regionalSourcing: true,
      sustainabilityScore: 65,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 180,
    },
    foodSafety: {
      certifications: ['IFS', 'ISO22000', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT001-2024-11-15',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: '2',
    sku: 'APT-002',
    name: 'Breaded Chicken Schnitzel',
    description: 'Breaded chicken schnitzel, crispy and golden',
    category: 'Poultry',
    price: 7.80,
    bulkPrice: 6.50,
    bulkMinQuantity: 12,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 28,
      carbs: 24,
      fat: 20,
      fiber: 2,
      sugar: 1,
      salt: 1.1,
      saturatedFat: 4,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.1,
      regionalSourcing: true,
      sustainabilityScore: 72,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 150,
    },
    foodSafety: {
      certifications: ['IFS', 'BRC', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT002-2024-11-18',
      storageConditions: 'Store at -18°C. Cook from frozen at 180°C for 20 minutes.',
    },
  },
  {
    id: '3',
    sku: 'APT-003',
    name: 'Mashed Potatoes',
    description: 'Creamy mashed potatoes, smooth and delicious',
    category: 'Sides',
    price: 3.20,
    bulkPrice: 2.80,
    bulkMinQuantity: 15,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1585232351592-856a2f2c4df3?w=400&h=300&fit=crop',
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 195,
      protein: 4,
      carbs: 32,
      fat: 6,
      fiber: 3,
      sugar: 2,
      salt: 0.9,
      saturatedFat: 3.5,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.25,
      regionalSourcing: true,
      sustainabilityScore: 88,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 100,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT003-2024-11-20',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: '4',
    sku: 'APT-004',
    name: 'Red Cabbage',
    description: 'Traditional German red cabbage with apples and spices',
    category: 'Vegetables',
    price: 3.50,
    bulkPrice: 3.00,
    bulkMinQuantity: 10,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 85,
      protein: 2,
      carbs: 18,
      fat: 0.5,
      fiber: 4,
      sugar: 12,
      salt: 0.6,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Recyclable pouch',
        recyclable: true,
        recycledContent: 65,
      },
      transportDistance: 120,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT004-2024-11-12',
      storageConditions: 'Store at -18°C or below. Can be heated from frozen.',
    },
  },
  {
    id: '5',
    sku: 'APT-005',
    name: 'Spätzle',
    description: 'Traditional Swabian egg noodles',
    category: 'Sides',
    price: 3.80,
    bulkPrice: 3.20,
    bulkMinQuantity: 12,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1612874292776-d399be7e8bdc?w=400&h=300&fit=crop',
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 285,
      protein: 9,
      carbs: 52,
      fat: 4,
      fiber: 2,
      sugar: 1,
      salt: 0.7,
      saturatedFat: 1.2,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.32,
      regionalSourcing: true,
      sustainabilityScore: 80,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 55,
      },
      transportDistance: 140,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT005-2024-11-19',
      storageConditions: 'Keep frozen at -18°C. Reheat in boiling water or microwave.',
    },
  },
  {
    id: '6',
    sku: 'APT-006',
    name: 'Beef Roulade',
    description: 'Beef roulade with bacon, pickles and mustard',
    category: 'Meat Dishes',
    price: 9.50,
    bulkPrice: 8.20,
    bulkMinQuantity: 8,
    unit: 'per portion (300g)',
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 485,
      protein: 38,
      carbs: 6,
      fat: 34,
      fiber: 1,
      sugar: 2,
      salt: 1.8,
      saturatedFat: 14,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 4.2,
      regionalSourcing: true,
      sustainabilityScore: 58,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 70,
      },
      transportDistance: 200,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT006-2024-11-14',
      storageConditions: 'Keep frozen at -18°C. Heat thoroughly to 75°C.',
    },
  },
  {
    id: '7',
    sku: 'APT-007',
    name: 'Pollock Fillet with Butter Sauce',
    description: 'Pollock fillet with delicate butter sauce',
    category: 'Fish',
    price: 8.20,
    bulkPrice: 7.00,
    bulkMinQuantity: 10,
    unit: 'per portion (180g)',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    allergens: ['fish', 'dairy'],
    nutritionalInfo: {
      calories: 245,
      protein: 28,
      carbs: 2,
      fat: 14,
      fiber: 0,
      sugar: 1,
      salt: 0.9,
      saturatedFat: 6,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 1.8,
      regionalSourcing: false,
      sustainabilityScore: 75,
      packaging: {
        type: 'Recyclable film',
        recyclable: true,
        recycledContent: 50,
      },
      transportDistance: 850,
    },
    foodSafety: {
      certifications: ['IFS', 'BRC', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT007-2024-11-16',
      storageConditions: 'Keep frozen at -18°C. Do not refreeze after thawing.',
    },
  },
  {
    id: '8',
    sku: 'APT-008',
    name: 'Green Beans',
    description: 'Fresh green beans, lightly seasoned',
    category: 'Vegetables',
    price: 3.20,
    bulkPrice: 2.70,
    bulkMinQuantity: 15,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 3,
      carbs: 12,
      fat: 0.5,
      fiber: 4,
      sugar: 3,
      salt: 0.3,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 95,
      packaging: {
        type: 'Recyclable plastic bag',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 120,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'EUOrganic'],
      euNutritionLabel: true,
      traceabilityCode: 'APT008-2024-11-18',
      storageConditions: 'Store at -18°C. Cook from frozen.',
    },
  },
  {
    id: '9',
    sku: 'APT-009',
    name: 'Boiled Potatoes',
    description: 'Classic boiled potatoes with salt',
    category: 'Sides',
    price: 2.80,
    bulkPrice: 2.40,
    bulkMinQuantity: 20,
    unit: 'per portion (250g)',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 180,
      protein: 4,
      carbs: 38,
      fat: 0.2,
      fiber: 3,
      sugar: 1,
      salt: 0.8,
      saturatedFat: 0.05,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.12,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 40,
      },
      transportDistance: 80,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT009-2024-11-21',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: '10',
    sku: 'APT-010',
    name: 'Roast Gravy',
    description: 'Rich, savory gravy perfect for meat dishes',
    category: 'Sauces',
    price: 12.50,
    bulkPrice: 10.80,
    bulkMinQuantity: 8,
    unit: '1L container',
    imageUrl: 'https://images.unsplash.com/photo-1605521560596-83f6afe9d2d2?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 2,
      carbs: 8,
      fat: 3,
      fiber: 0.5,
      sugar: 2,
      salt: 1.2,
      saturatedFat: 1.5,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.28,
      regionalSourcing: true,
      sustainabilityScore: 78,
      packaging: {
        type: 'Recyclable plastic bottle',
        recyclable: true,
        recycledContent: 55,
      },
      transportDistance: 160,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'APT010-2024-11-10',
      storageConditions: 'Refrigerate after opening. Use within 5 days.',
    },
  },
  {
    id: '11',
    sku: 'APT-011',
    name: 'Mixed Vegetables',
    description: 'Mixed vegetables with carrots, broccoli, and cauliflower',
    category: 'Vegetables',
    price: 3.50,
    bulkPrice: 3.00,
    bulkMinQuantity: 12,
    unit: 'per portion (200g)',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    allergens: [],
    nutritionalInfo: {
      calories: 75,
      protein: 3.5,
      carbs: 14,
      fat: 0.8,
      fiber: 5,
      sugar: 4,
      salt: 0.4,
      saturatedFat: 0.1,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 0.18,
      regionalSourcing: true,
      sustainabilityScore: 90,
      packaging: {
        type: 'PE plastic bag (recyclable)',
        recyclable: true,
        recycledContent: 60,
      },
      transportDistance: 150,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT011-2024-11-17',
      storageConditions: 'Store at -18°C or below. Can be cooked from frozen.',
    },
  },
  {
    id: '12',
    sku: 'APT-012',
    name: 'Königsberg Meatballs',
    description: 'Traditional meatballs in creamy caper sauce',
    category: 'Meat Dishes',
    price: 8.80,
    bulkPrice: 7.50,
    bulkMinQuantity: 10,
    unit: 'per portion (380g)',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',
    allergens: ['eggs', 'dairy'],
    nutritionalInfo: {
      calories: 425,
      protein: 26,
      carbs: 18,
      fat: 28,
      fiber: 1,
      sugar: 3,
      salt: 1.5,
      saturatedFat: 12,
    },
    inStock: true,
    sustainability: {
      co2Footprint: 2.8,
      regionalSourcing: true,
      sustainabilityScore: 68,
      packaging: {
        type: 'Recyclable tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 170,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'APT012-2024-11-13',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
];

export const ALLERGEN_LABELS: Record<string, { label: string; color: string }> = {
  nuts: { label: 'Nuts', color: 'bg-destructive text-destructive-foreground' },
  dairy: { label: 'Dairy', color: 'bg-warning text-warning-foreground' },
  gluten: { label: 'Gluten', color: 'bg-warning text-warning-foreground' },
  eggs: { label: 'Eggs', color: 'bg-warning text-warning-foreground' },
  soy: { label: 'Soy', color: 'bg-muted text-muted-foreground' },
  fish: { label: 'Fish', color: 'bg-destructive text-destructive-foreground' },
  shellfish: { label: 'Shellfish', color: 'bg-destructive text-destructive-foreground' },
  sesame: { label: 'Sesame', color: 'bg-muted text-muted-foreground' },
};

export const CONVERSATION_STARTERS = [
  "Find me budget-friendly protein options",
  "I need a gluten-free meal plan for lunch",
  "Show me high-protein, low-fat products",
  "What are my options for vegan breakfast?",
];

export const AGENT_CONVERSATION_STARTERS: Record<string, string[]> = {
  auto: [
    "Find me budget-friendly protein options",
    "I need a gluten-free meal plan for lunch",
    "Show me high-protein, low-fat products",
    "What are my options for vegan breakfast?",
  ],
  coordinator: [
    "Help me plan a week of meals",
    "I need products for 50 people",
    "What's the best way to save money?",
    "Show me balanced nutrition options",
  ],
  budget: [
    "What are your cheapest bulk options?",
    "Find me the best deals this week",
    "Show me cost per serving for pasta",
    "How much can I save buying in bulk?",
  ],
  nutrition: [
    "I need high-protein meal options",
    "Show me low-calorie products",
    "What are good sources of healthy fats?",
    "Find balanced meals under 500 calories",
  ],
  dietary: [
    "I need dairy-free alternatives",
    "Show me gluten-free options",
    "Find vegan protein sources",
    "What products are nut-free?",
  ],
  'meal-planning': [
    "Create a vegetarian lunch menu",
    "Plan breakfast for 30 people",
    "Show me complete dinner recipes",
    "I need ingredients for pasta dishes",
  ],
};

export const MOCK_ORDER_HISTORY: OrderHistory[] = [
  {
    id: 'order-001',
    date: Date.now() - 30 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[0],
        quantity: 10,
      },
      {
        product: MOCK_PRODUCTS[1],
        quantity: 12,
      },
      {
        product: MOCK_PRODUCTS[6],
        quantity: 5,
      },
    ],
    total: 1289.90,
    status: 'completed',
  },
  {
    id: 'order-002',
    date: Date.now() - 15 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[8],
        quantity: 15,
      },
      {
        product: MOCK_PRODUCTS[10],
        quantity: 8,
      },
      {
        product: MOCK_PRODUCTS[4],
        quantity: 4,
      },
    ],
    total: 746.00,
    status: 'completed',
  },
  {
    id: 'order-003',
    date: Date.now() - 7 * 24 * 60 * 60 * 1000,
    items: [
      {
        product: MOCK_PRODUCTS[2],
        quantity: 6,
      },
      {
        product: MOCK_PRODUCTS[11],
        quantity: 6,
      },
    ],
    total: 420.00,
    status: 'completed',
  },
];

export const MOCK_ORGANIZATION_PROFILE: OrganizationProfile = {
  id: 'org-001',
  name: "St. Mary's Regional Hospital",
  type: 'hospital',
  contactEmail: 'procurement@stmarys-hospital.com',
  contactPhone: '+1 (555) 234-5678',
  address: '1234 Healthcare Drive, Medical District, CA 90210',
  servingCapacity: 450,
  preferences: {
    dietaryRestrictions: ['vegetarian'],
    allergenExclusions: ['nuts', 'shellfish'],
    budgetPerServing: 3.75,
    specialRequirements: 'Halal certification required for all meat products. Prefer organic produce when available. Must meet hospital dietary standards for patient meals.',
    dietaryEnforcement: {
      requireVegetarianDaily: true,
      requireVeganDaily: false,
      minimumVegetarianPerWeek: 7,
      minimumVeganPerWeek: 0,
    },
  },
  orderHistory: MOCK_ORDER_HISTORY,
  createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
  updatedAt: Date.now(),
};

export const MOCK_MEALS: Meal[] = [
  {
    id: 'meal-1',
    name: 'Wheat-Based Veggie Schnitzel',
    description: 'Crispy vegetarian schnitzel on wheat basis',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1600803907087-f56d462fd26b?w=400&h=300&fit=crop',
    components: ['Veggie Schnitzel', 'Balkan-Style Sauce'],
    allergens: ['gluten', 'soy'],
    nutritionalInfo: {
      calories: 420,
      protein: 18,
      carbs: 48,
      fat: 16,
      fiber: 6,
      sugar: 4,
      salt: 1.2,
      saturatedFat: 2.5,
    },
    dietaryTags: ['Vegetarian'],
    price: 6.50,
    servingSize: '350g',
    sustainability: {
      co2Footprint: 0.8,
      regionalSourcing: true,
      sustainabilityScore: 82,
      packaging: {
        type: 'Recyclable cardboard tray',
        recyclable: true,
        recycledContent: 75,
      },
      transportDistance: 180,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'ISO22000'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL001-2024-11-20',
      storageConditions: 'Keep frozen at -18°C. Reheat to 75°C internal temperature.',
    },
  },
  {
    id: 'meal-2',
    name: 'Natural Green Beans',
    description: 'Natural green beans, lightly seasoned',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&h=300&fit=crop',
    components: ['Green Beans'],
    allergens: [],
    nutritionalInfo: {
      calories: 65,
      protein: 3,
      carbs: 12,
      fat: 0.5,
      fiber: 4,
      sugar: 3,
      salt: 0.3,
      saturatedFat: 0.1,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.20,
    servingSize: '200g',
    sustainability: {
      co2Footprint: 0.15,
      regionalSourcing: true,
      sustainabilityScore: 95,
      packaging: {
        type: 'Recyclable plastic film',
        recyclable: true,
        recycledContent: 50,
      },
      transportDistance: 120,
      seasonalProduct: true,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP', 'EUOrganic'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL002-2024-11-18',
      storageConditions: 'Store at -18°C or below. Cook from frozen.',
    },
  },
  {
    id: 'meal-3',
    name: 'Boiled Potatoes',
    description: 'Classic boiled potatoes with salt',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop',
    components: ['Boiled Potatoes'],
    allergens: [],
    nutritionalInfo: {
      calories: 180,
      protein: 4,
      carbs: 38,
      fat: 0.2,
      fiber: 3,
      sugar: 1,
      salt: 0.8,
      saturatedFat: 0.05,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 2.80,
    servingSize: '250g',
    sustainability: {
      co2Footprint: 0.12,
      regionalSourcing: true,
      sustainabilityScore: 92,
      packaging: {
        type: 'Biodegradable film',
        recyclable: true,
        recycledContent: 40,
      },
      transportDistance: 80,
      seasonalProduct: false,
    },
    foodSafety: {
      certifications: ['IFS', 'HACCP'],
      euNutritionLabel: true,
      traceabilityCode: 'MEAL003-2024-11-21',
      storageConditions: 'Keep frozen. Reheat thoroughly before serving.',
    },
  },
  {
    id: 'meal-4',
    name: 'Spring-Style Veggie Fricassee',
    description: 'Spring-style vegetarian fricassee with vegetables in cream sauce',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    components: [
      'Shredded Pea and Wheat Base',
      'Light Vegetable Sauce with Peas',
      'Carrots and Mushrooms',
    ],
    allergens: ['gluten', 'dairy', 'soy'],
    nutritionalInfo: {
      calories: 385,
      protein: 16,
      carbs: 42,
      fat: 18,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.20,
    servingSize: '400g',
  },
  {
    id: 'meal-5',
    name: 'Natural Baby Carrots',
    description: 'Natural baby carrots, tender and sweet',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop',
    components: ['Baby Carrots'],
    allergens: [],
    nutritionalInfo: {
      calories: 55,
      protein: 1.2,
      carbs: 11,
      fat: 0.3,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.50,
    servingSize: '200g',
  },
  {
    id: 'meal-6',
    name: 'Brown Rice',
    description: 'Wholesome natural brown rice',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    components: ['Brown Rice'],
    allergens: [],
    nutritionalInfo: {
      calories: 215,
      protein: 5,
      carbs: 45,
      fat: 1.8,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.00,
    servingSize: '200g',
  },
  {
    id: 'meal-7',
    name: 'Colorful Pointed Cabbage Stew (Vegetarian)',
    description: 'Colorful pointed cabbage vegetable stew',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1547928576-4a5a5c7781ef?w=400&h=300&fit=crop',
    components: ['Colorful Pointed Cabbage', 'Vegetable Mix'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 38,
      fat: 14,
    },
    dietaryTags: ['Vegetarian'],
    price: 6.80,
    servingSize: '380g',
  },
  {
    id: 'meal-8',
    name: 'Whole Grain Rolls',
    description: 'Hearty whole grain rolls',
    category: 'Bread',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    components: ['Whole Grain Rolls'],
    allergens: ['gluten'],
    nutritionalInfo: {
      calories: 245,
      protein: 8,
      carbs: 48,
      fat: 2.5,
    },
    dietaryTags: ['Vegetarian'],
    price: 1.50,
    servingSize: '80g',
  },
  {
    id: 'meal-9',
    name: 'Yogurt with Fruits',
    description: 'Creamy yogurt with fresh fruits',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
    components: ['Yogurt', 'Fruits'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 180,
      protein: 6,
      carbs: 28,
      fat: 4.5,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 2.50,
    servingSize: '150g',
  },
  {
    id: 'meal-10',
    name: 'Pumpkin Pasta',
    description: 'Tortellini in butternut squash sauce with quinoa vegetables',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    components: [
      'Tortellini in Butternut Squash Sauce',
      'With Arugula and Pumpkin Seeds',
      'Refined with Quinoa',
    ],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 465,
      protein: 18,
      carbs: 58,
      fat: 19,
    },
    dietaryTags: ['Vegetarian'],
    price: 8.50,
    servingSize: '420g',
  },
  {
    id: 'meal-11',
    name: 'Mixed Salad',
    description: 'Fresh mixed salad',
    category: 'Salad',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    components: ['Mixed Salad'],
    allergens: [],
    nutritionalInfo: {
      calories: 45,
      protein: 2,
      carbs: 8,
      fat: 0.5,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.80,
    servingSize: '150g',
  },
  {
    id: 'meal-12',
    name: 'Hearty Bread Casserole',
    description: 'Hearty casserole with broccoli, tomato and onions with cheese topping',
    category: 'Main',
    imageUrl: 'https://images.unsplash.com/photo-1604908815875-6d0e27bf6d0e?w=400&h=300&fit=crop',
    components: [
      'Bread Casserole with Broccoli',
      'Tomato and Onions',
      'Topped with Cheese',
    ],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 520,
      protein: 24,
      carbs: 52,
      fat: 24,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.80,
    servingSize: '450g',
  },
  {
    id: 'meal-13',
    name: 'Seasonal Fruit',
    description: 'Fresh seasonal fruit',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    components: ['Seasonal Fruit'],
    allergens: [],
    nutritionalInfo: {
      calories: 85,
      protein: 1,
      carbs: 20,
      fat: 0.3,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 2.80,
    servingSize: '150g',
  },
  {
    id: 'meal-14',
    name: 'Sliced Chicken Breast',
    description: 'Sliced chicken breast in creamy sauce',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    components: ['Chicken Breast', 'Creamy Sauce'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 385,
      protein: 32,
      carbs: 12,
      fat: 24,
    },
    dietaryTags: ['Gluten-Free'],
    price: 9.20,
    servingSize: '350g',
  },
  {
    id: 'meal-15',
    name: 'Salmon Fillet with Herb Crust',
    description: 'Salmon fillet with herb crust',
    category: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    components: ['Salmon Fillet', 'Herb Crust'],
    allergens: ['fish', 'gluten'],
    nutritionalInfo: {
      calories: 420,
      protein: 38,
      carbs: 8,
      fat: 26,
    },
    dietaryTags: ['Pescatarian'],
    price: 12.50,
    servingSize: '280g',
  },
  {
    id: 'meal-16',
    name: 'Roast Beef with Red Cabbage',
    description: 'Roast beef with red cabbage',
    category: 'Meat',
    imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=300&fit=crop',
    components: ['Roast Beef', 'Red Cabbage', 'Gravy'],
    allergens: [],
    nutritionalInfo: {
      calories: 485,
      protein: 42,
      carbs: 18,
      fat: 28,
    },
    dietaryTags: ['Gluten-Free'],
    price: 10.80,
    servingSize: '400g',
  },
  {
    id: 'meal-17',
    name: 'Mashed Potatoes',
    description: 'Creamy mashed potatoes',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1585232351592-856a2f2c4df3?w=400&h=300&fit=crop',
    components: ['Mashed Potatoes'],
    allergens: ['dairy'],
    nutritionalInfo: {
      calories: 195,
      protein: 4,
      carbs: 32,
      fat: 6,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 3.20,
    servingSize: '250g',
  },
  {
    id: 'meal-18',
    name: 'Mixed Vegetables',
    description: 'Mixed vegetables medley',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    components: ['Carrots', 'Broccoli', 'Cauliflower'],
    allergens: [],
    nutritionalInfo: {
      calories: 75,
      protein: 3.5,
      carbs: 14,
      fat: 0.8,
    },
    dietaryTags: ['Vegan', 'Gluten-Free'],
    price: 3.50,
    servingSize: '200g',
  },
  {
    id: 'meal-19',
    name: 'Spätzle',
    description: 'Traditional German egg noodles',
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1612874292776-d399be7e8bdc?w=400&h=300&fit=crop',
    components: ['Spätzle'],
    allergens: ['gluten', 'eggs'],
    nutritionalInfo: {
      calories: 285,
      protein: 9,
      carbs: 52,
      fat: 4,
    },
    dietaryTags: ['Vegetarian'],
    price: 3.80,
    servingSize: '250g',
  },
  {
    id: 'meal-20',
    name: 'Tiramisu',
    description: 'Classic Italian dessert',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
    components: ['Mascarpone', 'Espresso', 'Ladyfingers'],
    allergens: ['gluten', 'dairy', 'eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 7,
      carbs: 42,
      fat: 20,
    },
    dietaryTags: ['Vegetarian'],
    price: 4.50,
    servingSize: '150g',
  },
  {
    id: 'meal-21',
    name: 'Thai Peanut Noodles',
    description: 'Spicy noodles with peanut sauce and vegetables',
    category: 'Vegetarian',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    components: ['Rice Noodles', 'Peanut Sauce', 'Mixed Vegetables', 'Crushed Peanuts'],
    allergens: ['nuts', 'soy', 'gluten'],
    nutritionalInfo: {
      calories: 520,
      protein: 18,
      carbs: 62,
      fat: 24,
    },
    dietaryTags: ['Vegetarian'],
    price: 7.80,
    servingSize: '400g',
  },
  {
    id: 'meal-22',
    name: 'Almond-Crusted Chicken',
    description: 'Tender chicken breast with crunchy almond coating',
    category: 'Poultry',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    components: ['Chicken Breast', 'Almond Crust', 'Herb Seasoning'],
    allergens: ['nuts', 'eggs'],
    nutritionalInfo: {
      calories: 445,
      protein: 38,
      carbs: 12,
      fat: 28,
    },
    dietaryTags: ['Gluten-Free'],
    price: 10.50,
    servingSize: '350g',
  },
  {
    id: 'meal-23',
    name: 'Walnut & Spinach Salad',
    description: 'Fresh spinach salad with candied walnuts and goat cheese',
    category: 'Salad',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    components: ['Fresh Spinach', 'Candied Walnuts', 'Goat Cheese', 'Balsamic Vinaigrette'],
    allergens: ['nuts', 'dairy'],
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 18,
      fat: 24,
    },
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    price: 6.50,
    servingSize: '280g',
  },
  {
    id: 'meal-24',
    name: 'Pecan-Crusted Salmon',
    description: 'Atlantic salmon with maple pecan crust',
    category: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    components: ['Atlantic Salmon Fillet', 'Pecan Crust', 'Maple Glaze'],
    allergens: ['fish', 'nuts'],
    nutritionalInfo: {
      calories: 485,
      protein: 36,
      carbs: 18,
      fat: 32,
    },
    dietaryTags: ['Pescatarian', 'Gluten-Free'],
    price: 13.50,
    servingSize: '320g',
  },
];
